// INGREDIENT ACTION TYPES
export const FETCH_INGREDIENTS = "FETCH_PRODUCTS";
// export const DELETE_INGREDIENT = "DELETE_PRODUCT";
// export const CREATE_INGREDIENT = "CREATE_PRODUCT";
// export const UPDATE_INGREDIENT = "UPDATE_PRODUCT";

// CATEGORY ACTION TYPES
export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
// export const CREATE_SHOP = "CREATE_SHOP";
