// INGREDIENT ACTION TYPES
export const FETCH_INGREDIENTS = "FETCH_INGREDIENTS";
export const CREATE_INGREDIENT = "CREATE_INGREDIENT";

// CATEGORY ACTION TYPES
export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const CREATE_CATEGORY = "CREATE_CATEGORY";
